%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 520.908620
Camera.fy: 521.007327
Camera.cx: 325.141442
Camera.cy: 249.701764

Camera.k1: 0.231222
Camera.k2: -0.784899
Camera.p1: -0.003257
Camera.p2: -0.000105
Camera.k3: 0.917205

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor 
DepthMapFactor: 5208.0


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

Viewer.pangolin: 1
Viewer.rviz: 1
Viewer.readlocalobject: 0
Viewer.show_object3d_frame: 1

#--------------------------------------------------------------------------------------------
# PointCloud Mapping
#--------------------------------------------------------------------------------------------
PointCloudMapping.Resolution: 0.01

#---------------------------------------------------------------------------------------------
# Semantic Mapping
#---------------------------------------------------------------------------------------------
Semantic.Model: 0 # Yolov5: 0
Semantic.ModelPath: "/home/lacie/slam_ws/src/junbot_planner/orb_slam3_ros/config/Model"
Semantic.ObjectOptimize: 1

#--------------------------------------------------------------------------------------------
# octoMap Parameters
#--------------------------------------------------------------------------------------------
octoMap.res: 0.05

#--------------------------------------------------------------------------------------------
# Dynamic point
#--------------------------------------------------------------------------------------------
Dynamic.flow: 10.0

#--------------------------------------------------------------------------------------------
# 3D cuboid
#--------------------------------------------------------------------------------------------
IE.rows: 18
IE.cols: 18
IE.P_occ: 0.6
IE.P_free: 0.4
IE.P_prior: 0.5
IE.Threshold: 5

#--------------------------------------------------------------------------------------------
# MapPublisher
#--------------------------------------------------------------------------------------------
# 1: robot_camera tf; 2: use imu
ConstraintType: 1
Trobot_camera.qx: 0.0003
Trobot_camera.qy: 0.8617
Trobot_camera.qz: -0.5072
Trobot_camera.qw: -0.0145
Trobot_camera.tx: 0.0 #-0.6832
Trobot_camera.ty: 0.0 #2.6909
Trobot_camera.tz: 1.7373
